// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wruxfdeirogmwkvqoeyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydXhmZGVpcm9nbXdrdnFvZXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mzg1NzIsImV4cCI6MjA2NTMxNDU3Mn0.CVrFvgJL1PhU5FWquiM9Jz5Q9GYqDgCpYkef0_SZGHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);